# Generated by Django 6.0 on 2026-02-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0003_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='prodimg/'),
        ),
    ]
