# Generated by Django 6.0 on 2026-02-09 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0004_product_prod_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExteriorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exteriorimg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_images', to='cbvapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='interiorimg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_images', to='cbvapp.product')),
            ],
        ),
    ]
